metrics_titles = [
    "Difficulty",
    "Experience",
    "Skillset",
    "Aptitude Focus",
    "Technical Focus",
    "HR Focus",
    "Experience Level Categorization",
    "Technical Skill Emphasis",
    "Domain Knowledge Emphasis",
    "Aptitude Test Skill Split",
    "Technical Test Skill Split",
    "Question Format Diversity",
    "Skill Proficiency Levels",
    "Skill Importance Weights",
    "Contextual Question Scenarios",
    "Test Time Allocation",
    "Code Writing Emphasis",
    "Programming Language Prioritization",
    "HR Round Focus Areas",
    "Behavioral Competencies Tested",
    "Situational Judgment Scenarios"
]